name: 🐞 Reporte de error legal / falso positivo
description: Reporta una incidencia en el análisis semántico jurídico
title: "[Bug] "
labels: ["bug", "legal", "analisis"]
assignees:
  - validUser123
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ Gracias por contribuir a mejorar el validador semántico jurídico.

  - type: input
    id: archivo-afectado
    attributes:
      label: Archivo/documento afectado
      description: Indica el nombre del archivo (PDF/DOCX/TXT) en el que se produjo el error
      placeholder: "ejemplo: Acta_JGE_2025.pdf"
    validations:
      required: true

  - type: textarea
    id: error-detectado
    attributes:
      label: Descripción del error
      description: Explica en qué consiste el error legal detectado
      placeholder: Se clasificó como 'coeficiente' pero era un título notarial...
    validations:
      required: true

  - type: textarea
    id: contenido-relevante
    attributes:
      label: Extracto relevante del documento
      description: Añade un fragmento del texto que se analizó mal
      placeholder: El acta mencionaba “porcentaje de participación” sin especificar coeficiente...
    validations:
      required: false

  - type: dropdown
    id: gravedad
    attributes:
      label: Nivel de gravedad
      options:
        - Baja
        - Media
        - Alta
    validations:
      required: true