name: ✨ Sugerencia de mejora / nueva funcionalidad
description: Propón una funcionalidad nueva o mejora en el validador semántico jurídico
title: "[Feature] "
labels: ["enhancement", "sugerencia", "semántico"]
assignees:
  - "kabehz"
projects:
  - "Semántico"
  - "Sugerencias"
  - "Mejoras"
  - "Funcionalidades"
  - "Validación"
  - "Legal"
  - "Jurídico"
  - "Abogacía"
  - "Ley de Propiedad Horizontal"
  - "Ley de Propiedad Intelectual"
  - "Ley de Protección de Datos"
body:
  - type: markdown
    attributes:
      value: |
        🙌 ¡Gracias por sugerir mejoras! Cuéntanos cómo podemos hacer el validador más útil.

  - type: input
    id: nombre-funcionalidad
    attributes:
      label: Nombre corto de la mejora
      placeholder: Ej. "Incluir detección de cláusulas abusivas"
    validations:
      required: true

  - type: textarea
    id: descripcion
    attributes:
      label: ¿En qué consiste la mejora?
      description: Detalla qué quieres que haga el sistema
      placeholder: Me gustaría que el sistema identifique cláusulas que violen la Ley de Propiedad Horizontal...
    validations:
      required: true

  - type: textarea
    id: uso-previsto
    attributes:
      label: ¿Qué problema resuelve?
      description: Describe el caso de uso o beneficio
      placeholder: Evitar decisiones unilaterales ocultas en estatutos mal redactados...
    validations:
      required: true

  - type: dropdown
    id: prioridad
    attributes:
      label: Prioridad sugerida
      options:
        - Baja
        - Media
        - Alta
    validations:
      required: true