name: CI con OPA + Pytest
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      opa:
        image: openpolicyagent/opa:latest
        ports: [8181:8181]
        volumes: [./policies:/policies]
        options: --entrypoint "/opa run --server /policies"
    steps:
      - uses: actions/checkout@v3
      - run: pip install -r requirements-dev.txt
      - run: pytest
      - uses: actions/upload-artifact@v3
        with:
          name: coverage-html
          path: htmlcov/
