name: CI/CD Multitecnología

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -r src/pip/legal-validator/requirements.txt
      - name: Run Python tests
        run: |
          pytest tests/python/

  test-bash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Bash script tests
        run: bash tests/bash/test_scripts.sh

  test-terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init & Validate
        run: |
          cd src/iac/terraform
          terraform init
          terraform validate

  test-ansible:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
      - name: Check Ansible syntax
        run: |
          ansible-playbook --syntax-check src/iac/ansible/playbook.yml