name: CI con OPA + Pytest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      opa:
        image: openpolicyagent/opa:latest
        ports:
          - 8181:8181
        volumes:
          - ./policies:/policies
        options: --entrypoint "/opa run --server /policies"

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements-dev.txt

      - name: Esperar que OPA esté activo
        run: |
          for i in {1..10}; do curl -s http://localhost:8181/health || sleep 1; done

      - name: Ejecutar pruebas
        run: |
          source .venv/bin/activate
          pytest