name: Post-Merge Badges Updater
on:
  push:
    branches:
      - main
      - release
      - site
      - documentation
      - desarrollo
      - media
      - admin
      - bussines


jobs:
  update-readme-badges:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Insertar badges de MkDocs
        run: bash scripts/insert_mkdocs_badges.sh

      - name: Commit cambios si README modificado
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "🔖 Inserción automática de badges MkDocs tras merge"
          REPO_URL="https://x-access-token:${GITHUB_TOKEN}'@github.com/${GITHUB_REPOSITORY}.git"
          git push "$REPO_URL" HEAD:${GITHUB_REF#refs/heads/}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_REPOSITORY: ${{ github.repository }}