name: Publicar Artefactos de Análisis

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  analizar:
    runs-on: ubuntu-latest
    name: Ejecutar análisis y guardar artefactos
    steps:
      - uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Ejecutar análisis (demo)
        run: |
          mkdir salida_demo
          python validador_service_v4.py Anexos_Ejemplo salida_demo

      - name: Publicar artefactos
        uses: actions/upload-artifact@v4
        with:
          name: resultados-validador
          path: salida_demo/