name: Update MkDocs Index

on:
  push:
    paths:
      - 'docs/**/*.md'
      - '.github/workflows/update_mkdocs.yml'
  pull_request:
    paths:
      - 'docs/**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install PyYAML
        run: pip install pyyaml

      - name: Regenerate mkdocs.yml
        run: python scripts/generate_mkdocs.py

      - name: Commit and push mkdocs.yml
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add mkdocs.yml
          git commit -m "🔄 Auto-update mkdocs index" || echo "No changes"
          git push || echo "No changes to push"